name: devfest_levante_2018
description: Official app of DevFest Levante 2018.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

  cloud_firestore: ^0.7.3     # new, firestore library
  intl: ^0.15.7               # new, datetime and localization library
  google_sign_in: ^3.0.4      # new, required by Firebase Auth
  firebase_auth: ^0.5.15      # new, Firebase Auth library
  firebase_messaging:         # new, Firebase Push Notification library
  flutter_statusbar_manager : ^1.0.0
  flutter_map: ^0.0.1
  url_launcher: ^3.0.3
  share: ^0.5.2
  flutter_local_notifications:
#  android_alarm_manager: ^0.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/

  #  - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Thin.ttf
          weight: 100

